modLoader = "javafml"
loaderVersion = "[43,)"
license = "LGPL-3.0"
issueTrackerURL = "https://github.com/MayaqqDev/Estrogen/issues"
[[mods]]
modId = "estrogen"
version = "${version}-forge"
displayName = "Create: Estrogen"
logoFile = "icon.png"
credits="${contributors}"
authors = "Mayaqq"

# Description
description = '''
Create Addon Based around expressing yourself, fluid handling and expanding your factory. This mods add a lot of new Items, Blocks, Mechanics and more!
'''

# forge
[[dependencies.estrogen]] #optional
modId = "forge"
mandatory = true
versionRange = "[43,)"
# BEFORE, AFTER or NONE
ordering = "NONE"
# BOTH, CLIENT or SERVER
side = "BOTH"
# minecraft
[[dependencies.estrogen]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"
# create
[[dependencies.estrogen]]
modId="create"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"
# curios
[[dependencies.estrogen]]
modId="curios"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"
# architectury api
[[dependencies.estrogen]]
modId="architectury"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"